name: Build daily
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    name: Build neovim
    runs-on: ubuntu-18.04

    container:
      image: "ghcr.io/void-linux/xbps-src-masterdir:20220527RC01-${{ matrix.config.bootstrap }}"
      env:
        PATH: "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin"
        ARCH: "${{ matrix.config.arch }}"
        BOOTSTRAP: "${{ matrix.config.bootstrap }}"
        LIBC: "${{ matrix.config.libc }}"

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        config:
          - { arch: x86_64, bootstrap: x86_64, libc: glibc }
          # - { arch: i686, bootstrap: i686, test: 1 }
          # - { arch: aarch64, bootstrap: x86_64, test: 0 }
          # - { arch: armv7l, bootstrap: x86_64, test: 0 }
          - { arch: x86_64-musl, bootstrap: x86_64-musl, libc: musl }
          # - { arch: armv6l-musl, bootstrap: x86_64-musl, test: 0 }
          # - { arch: aarch64-musl, bootstrap: x86_64-musl, test: 0 }

    steps:
      - name: Prepare container
        run: |
          echo "repository=https://ram02z.github.io/neovim-nightly/$LIBC" > /etc/xbps.d/11-neovim-nightly.conf
          # Sync and upgrade once, assume error comes from xbps update
          xbps-install -Syu || xbps-install -yu xbps
          # Upgrade again (in case there was a xbps update)
          xbps-install -yu
          # Install git and other dependencies for the scripts
          xbps-install -y git wget curl make jq tar

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Clone void-packages
        run: make clone

      - name: Configure xbps-src
        run: bash scripts/configure.sh

      - name: Generate template
        run: make template

      - name: Build nvim
        run: make build

      - run: 'echo "$PRIVATE_PEM" > private.pem'
        shell: bash
        env:
          PRIVATE_PEM: ${{ secrets.PRIVATE_PEM }}

      - run: 'echo "$PRIVATE_PEM_PUB" > private.pem.pub'
        shell: bash
        env:
          PRIVATE_PEM_PUB: ${{ secrets.PRIVATE_PEM_PUB }}

      - name: Sign nvim
        run: make sign

      - name: Generate index.html
        run: make tree

      - name: Check contents of binkpkgs
        run: ls -la ./void-packages/hostdir/binpkgs

      - name: Deploy to GitHub Pages
        run: make deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
