name: Build daily
on:
  push:
    branches:
      - master
  # schedule:
    # - cron: '0 0 1-31 * *'


jobs:
  build:
    name: Build neovim
    runs-on: ubuntu-latest

    container:
      image: 'ghcr.io/void-linux/xbps-src-masterdir@sha256:0e3021fba6415e2e933eecabb28d8f8256e7bd5347e7b281633a61fa42ea3820'
      env:
        PATH: '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/tmp/bin'

    steps:
      - name: Prepare container
        run: |
          # Sync and upgrade once, assume error comes from xbps update
          xbps-install -Syu || xbps-install -yu xbps
          # Upgrade again (in case there was a xbps update)
          xbps-install -yu
          # Install git and other dependencies for the scripts
          xbps-install -y git wget curl make jq tar rsync
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Clone void-packages
        run: make clone

      - name: Configure xbps-src
        run: bash scripts/configure.sh

      - name: Generate template
        run: make template

      - name: Build nvim
        run: make build

      - run: 'echo "$PRIVATE_PEM" > private.pem'
        shell: bash
        env:
          PRIVATE_PEM: ${{ secrets.PRIVATE_PEM }}

      - run: 'echo "$PRIVATE_PEM_PUB" > private.pem.pub'
        shell: bash
        env:
          PRIVATE_PEM_PUB: ${{ secrets.PRIVATE_PEM_PUB }}

      - name: Sign nvim
        run: make sign

      - name: Generate index.html
        run: make tree

      - name: Fix missing release file
        run : make fix_release

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: void-packages/hostdir/binpkgs

